config/routes.rb
# frozen_string_literal: true

require "sidekiq/web"

Rails.application.routes.draw do
  namespace :admin do
    get "/auth/google_oauth2/callback", to: "sessions#create"
    get "/auth/failure", to: redirect("/401", 302)

    get "/login", to: "sessions#new"
    get "/logout", to: "sessions#destroy"

    constraints AdminConstraint.new do
      mount Sidekiq::Web, at: "/sidekiq"

      root to: redirect("/admin/sidekiq", 302)
    end
  end

  mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?

  resources :academic_degree_terms, only: [] do
    resources :agendas, except: :show, param: :token, shallow: true do
      get "/", to: redirect("/agendas/%{agenda_token}/schedules", 302)

      resources :schedules, only: :index, constraints: ->(r) { r.params.fetch(:page, "1") =~ /^[1-9]\d*$/ } do
        get :processing, on: :collection
      end
    end
  end

  resources :agendas, param: :token, only: [] do
    resources :schedules, only: :show, param: :index, constraints: { index: /[1-9]\d*/ }
  end

  resource :faq, only: :show

  resources :terms, only: :index do
    collection do
      post :create_newsletter_subscription
    end
  end

  ErrorsController::MAPPED_ERRORS.each do |status, code|
    get "/#{code}", to: "errors##{status}", as: status
  end

  root "terms#index"
end

app/models/schedule.rb
# frozen_string_literal: true

class Schedule < ApplicationRecord
  belongs_to :agenda

  serialize :course_groups, CourseGroupsSerializer

  def starts_at
    @starts_at ||= weekdays.reject(&:empty?).min_by(&:starts_at).starts_at
  end

  def ends_at
    @ends_at ||= weekdays.reject(&:empty?).max_by(&:ends_at).ends_at
  end

  def duration
    (ends_at.hour - starts_at.hour) * 60
  end

  def weekdays
    @weekdays ||= (0..6).collect do |index|
      periods = weekday_courses[index] + weekday_leaves[index]
      ScheduleWeekday.new(index: index, periods: periods)
    end
  end

  private

  def weekday_courses
    @weekday_courses ||= ScheduleCourseBuilder.new(course_groups).call
  end

  def weekday_leaves
    @weekday_leaves ||= ScheduleLeaveBuilder.new(agenda.leaves).call
  end
end

app/controllers/schedules_controller.rb
# frozen_string_literal: true

class SchedulesController < ApplicationController
  include AgendaEagerLoading
  include SchedulePaginationHelper

  before_action :find_agenda
  before_action :ensure_not_processing,
                :ensure_schedules_present, only: :index
  before_action :ensure_processing, only: :processing
  before_action :eager_load_courses, except: :processing
  skip_before_action :show_navigation, only: :processing

  helper_method :course_colors

  def index
    @schedules = find_schedules || raise(ActiveRecord::RecordNotFound)
  end

  def show
    @schedule = @agenda.schedules.offset(schedule_index).first!
  end

  def processing
    render :processing, status: :accepted
  end

  private

  def agenda_token
    params.require(:agenda_token)
  end

  def find_schedules
    @agenda.schedules.page(params[:page]).per(SCHEDULES_PER_PAGE).presence
  end

  def ensure_schedules_present
    return unless @agenda.schedules.empty?

    redirect_to edit_agenda_path(token: @agenda.token), flash: { notice: t(".blank_agenda") }
  end

  def ensure_not_processing
    redirect_to action: :processing if @agenda.processing?
  end

  def ensure_processing
    redirect_to action: :index unless @agenda.processing?
  end

  def course_colors
    @course_colors ||= CourseColorMap.new(@agenda.courses)
  end
end

app/helpers/schedule_helper.rb
# frozen_string_literal: true
module ScheduleHelper
  SCHEDULES_PER_PAGE = 20

  def schedule_page_index
    (@schedules.current_page - 1) * @schedules.limit_value
  end

  def schedule_index
    Integer(params.fetch(:index)) - 1
  end

  def schedule_page
    schedule_index / SCHEDULES_PER_PAGE + 1
  end
end

app/helpers/schedules_helper.rb
# frozen_string_literal: true

module SchedulesHelper
  include ScheduleWeekdaysHelper

  def schedule_css_class(schedule)
    classes = %W[from-#{schedule_from(schedule)} duration-#{schedule_duration(schedule)}]
    classes << "collapsible" if schedule_collapsible?(schedule)
    classes.join(" ")
  end

  def schedule_hours(schedule)
    (schedule.starts_at.hour..schedule_restricted_ends_at(schedule)).collect do |hour|
      "#{hour.to_s.rjust(2, '0')}:00"
    end
  end

  private

  def schedule_duration(schedule)
    (schedule_restricted_ends_at(schedule) - schedule.starts_at.hour) * 60
  end

  def schedule_from(schedule)
    schedule.starts_at.hour * 60
  end

  def schedule_collapsible?(schedule)
    schedule.weekdays.select(&:weekend?).all?(&method(:schedule_weekday_collapsible?))
  end

  def schedule_restricted_ends_at(schedule)
    [schedule.ends_at.hour, 23].min
  end
end

app/views/schedules/_overview.html.haml
= render layout: "shared/overview", locals: { agenda: agenda, f: f } do
  .form-group
    = f.label :courses_per_schedule, class: "col-sm-4 control-label"
    .col-sm-8
      = f.text_field :courses_per_schedule, disabled: true, readonly: true, class: "form-control"

  .form-group
    = f.label :schedules_count, class: "col-sm-4 control-label"
    .col-sm-8
      = f.text_field :schedules_count, disabled: true, readonly: true, class: "form-control"

  .row
    .col-sm-offset-4.col-sm-8
      %table.table.courses-selected
        %thead
          %tr
            %th{ colspan: 2 }= t(".courses_selected")
            %th= t(".course_groups")
        %tbody
          - agenda.courses.each do |course|
            %tr
              %td
                - if course.mandatory?
                  %i.fa.fa-lock
                - else
                  %i.fa.fa-unlock
              %td
                %span.label.label-default{ class: course_color_css_class(course_colors, course.code) }= course.code
              %td
                - course.group_numbers.each do |group_number|
                  %span.label.label-default{ class: course_color_css_class(course_colors, course.code) }= group_number

app/views/schedules/_schedule.html.haml
%a{ id: "schedule-#{index}" }
%fieldset.schedule{ class: schedule_css_class(schedule) }
  %legend
    = link_to t(".title", index: index), agenda_schedule_path(agenda, index)

  .schedule-content
    %table.hours
      %thead
        %tr
          %th.weekday
      %tbody
        - schedule_hours(schedule).each do |hour|
          %tr.hour
            %td= hour
          %tr.half-hour
            %td

    .week-container
      %table.backdrop
        %thead
          %tr
            - schedule.weekdays.each do |weekday|
              %th.weekday{ class: schedule_weekday_backdrop_class(weekday) }
                %span= schedule_weekday_name(weekday)[0..2]
                %span.post= schedule_weekday_name(weekday)[3..]
        %tbody
          - schedule_hours(schedule).each do
            %tr.hour
              - schedule.weekdays.each do |weekday|
                %td.empty{ class: schedule_weekday_backdrop_class(weekday) }
            %tr.half-hour
              - schedule.weekdays.each do |weekday|
                %td.empty{ class: schedule_weekday_backdrop_class(weekday) }

      .week
        - schedule.weekdays.each do |weekday|
          .weekday{ class: schedule_weekday_css_class(weekday) }
            = render weekday.periods

app/views/schedules/_schedule_course.html.haml
.period{class: schedule_course_css_class(schedule_course)}
  %div= weekday_time_time_span(schedule_course)
  %div= schedule_course_format(schedule_course)
  %div= schedule_course.type

app/views/schedules/_schedule_leave.html.haml
.period.leave{class: schedule_leave_css_class(schedule_leave)}
  %div= weekday_time_time_span(schedule_leave)
  %div= t('.title')

app/views/schedules/index.html.haml
.container
  = render "shared/breadcrumb"

  %h1.page-header
    = t(".title")
    = link_to edit_agenda_path(token: @agenda.token), class: "btn btn-xs btn-primary" do
      %i.glyphicon.glyphicon-pencil
      = t(".edit")

= form_for @agenda do |f|
  = render "overview", agenda: @agenda, f: f

.container-fluid.schedules
  - @schedules.each_slice(2).with_index do |schedules_slice, slice_index|
    .row
      - schedules_slice.each_with_index do |schedule, index|
        .col-lg-6
          = render schedule, agenda: @agenda,
            index: schedule_page_index(@schedules) + index + (slice_index * 2) + 1, cache: true
= paginate @schedules, window: 2

app/views/schedules/processing.html.haml
.sk-folding-cube
  .sk-cube1.sk-cube
  .sk-cube2.sk-cube
  .sk-cube4.sk-cube
  .sk-cube3.sk-cube
%h1= t(".message")

app/views/schedules/show.html.haml
= form_for @agenda do |f|
  = render "overview", agenda: @agenda, f: f

.container
  .row
    = render @schedule, agenda: @agenda, index: schedule_index + 1
  .row
    = link_to agenda_schedules_path(page: schedule_page, anchor: "schedule-#{schedule_index + 1}") do
      %i.glyphicon.glyphicon-chevron-left
      = t(".back")