config/routes.rb
# frozen_string_literal: true

require "sidekiq/web"

Rails.application.routes.draw do
  namespace :admin do
    get "/auth/google_oauth2/callback", to: "sessions#create"
    get "/auth/failure", to: redirect("/401", 302)

    get "/login", to: "sessions#new"
    get "/logout", to: "sessions#destroy"

    constraints AdminConstraint.new do
      mount Sidekiq::Web, at: "/sidekiq"

      root to: redirect("/admin/sidekiq", 302)
    end
  end

  mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?

  resources :academic_degree_terms, only: [] do
    resources :agendas, except: :show, param: :token, shallow: true do
      get "/", to: redirect("/agendas/%{agenda_token}/schedules", 302)

      resources :schedules, only: :index, constraints: ->(r) { r.params.fetch(:page, "1") =~ /^[1-9]\d*$/ } do
        get :processing, on: :collection
      end
    end
  end

  resources :agendas, param: :token, only: [] do
    resources :schedules, only: :show, param: :index, constraints: { index: /[1-9]\d*/ }
  end

  resource :faq, only: :show

  resources :terms, only: :index do
    collection do
      post :create_newsletter_subscription
    end
  end

  ErrorsController::MAPPED_ERRORS.each do |status, code|
    get "/#{code}", to: "errors##{status}", as: status
  end

  root "terms#index"
end

app/views/shared/_breadcrumb.html.haml
%ol.breadcrumb
  - breadcrumb(@agenda, step).render do
    - links.each do |link|
      %li= link
    %li.active= current_name

app/views/shared/_flash_messages.html.haml
- flash.each do |type, _|
  .alert{ class: alert_class(type), role: "alert" }
    %span.glyphicon.glyphicon-exclamation-sign{ "aria-hidden" => true }
    = flash.now[type]

app/views/shared/_footer.html.haml
%footer.footer
  .container
    %p= t(".message_html")

app/views/shared/_google_analytics.html.erb
<% if analytics_tracking_id.present? %>
  <!-- Global site tag (gtag.js) - Google Analytics -->
  <script async src="https://www.googletagmanager.com/gtag/js?id=<%== analytics_tracking_id.to_json %>"></script>
  <script>
    window.dataLayer = window.dataLayer || [];
    function gtag(){dataLayer.push(arguments);}
    gtag('js', new Date());

    gtag('config', '<%== analytics_tracking_id.to_json %>');
  </script>
<% end %>

app/views/shared/_navbar.html.haml
%nav.navbar.navbar-inverse
  .container
    .navbar-header
      %button.navbar-toggle.collapsed{ "aria-expanded" => false,
                                      data: { toggle: "collapse", target: "#main-navigation" },
                                      type: "button" }
        %span.sr-only Toggle navigation
        %span.icon-bar
        %span.icon-bar
        %span.icon-bar
      = link_to root_path, class: "navbar-brand" do
        %i.glyphicon.glyphicon-th-large
        Rubik

    .navbar-collapse.collapse#main-navigation
      %ul.nav.navbar-nav
        %li= link_to t(".comments"), "https://github.com/Krystosterone/rubik/issues/new"
        %li= link_to t(".faq"), faq_path

app/views/shared/_overview.html.haml
.well
  .container
    .form-horizontal
      .form-group
        = label_tag :term_title, t(".term_title"), class: "col-sm-4 control-label"
        .col-sm-8
          = text_field_tag :term_title, term_title(agenda.term), disabled: true, readonly: true, class: "form-control"

      .form-group
        = label_tag :academic_degree_name, t(".academic_degree_name"), class: "col-sm-4 control-label"
        .col-sm-8
          = text_field_tag :academic_degree_name, agenda.academic_degree_name, disabled: true, readonly: true,
            class: "form-control"

      = yield